### ISSUE TITLE
Got failure with unit test

### ISSUE THREAD

**Issue by autumnw** [concourse/flight-school#2]
Hi,

I got the error as the following:
ailures:

  1) The FlightSchool application shows facts about a particular airport
     Failure/Error: decoded.fetch("weather").fetch("weather"),
     
     KeyError:
       key not found: "weather"
     # ./lib/radar.rb:26:in `fetch'
     # ./lib/radar.rb:26:in `status_for'
     # ./lib/app.rb:13:in `block in <class:FlightSchool>'
     # /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'

So what could be the problem?

**Comment by vito** [comment]
Could have been a network issue with the weather API. Not sure if we could change anything there since the error would have been on their end. Good to know, though; maybe we should remove the dependency on them.
