### ISSUE TITLE
Fligth school corrections

### ISSUE THREAD

**Issue by mkrogh** [concourse/flight-school#7]
## Overall

Error output does not look the same as in the document. 

All red and:
```
hijack: Backend error: Exit status: 500, message: {"Type":"","Message":"runc exec: exit status 1: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"./flight-school/ci/test.sh\\\": stat ./flight-school/ci/test.sh: no such file or directory\"\n","Handle":""}

errored
```

Which is actually much harder to read than the error message in the examples.

## Missing steps

- Creating the first script test.sh you need to make the directory `ci` in your flight-school folder. And perhaps better doc about `input`.
- Starting a pipeline, please add something like "Let us create a pipeline: `ci/pipeline.yml`" 
- In general frontload all the filenames and paths. At least I followed along while reading.

Other than that thanks for a step by step, make errors along the way first guide.

**Comment by chendrix** [comment]
Moved to concourse/concourse#1143
